# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='zotero_id',
        ),
        migrations.AddField(
            model_name='source',
            name='zotero_key',
            field=models.CharField(default='QA7RR4ZC', max_length=8),
            preserve_default=False,
        ),
    ]
